import type { Metadata, NextPage } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/assets/Theme";
import App from "./providers";
import AppBarWrapper from "./components/AppBar/AppBarWrapper";
import { AppProps } from "next/app";
import { ReactElement, ReactNode } from "react";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} antialiased`}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <App>{children}</App>
        </ThemeProvider>
      </body>
    </html>
  );
}
